[[main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 10

[[main]]
  identifier = "posts"
  name = "所思所想"   # 这里对应你的 content/posts 文件夹
  url = "/posts/"
  weight = 20

[[main]]
  identifier = "notes"
  name = "学习笔记"   # 对应 content/notes 文件夹
  url = "/notes/"
  weight = 30

[[main]]
  identifier = "plan"
  name = "生涯规划"   # 对应 content/plan 文件夹
  url = "/plan/"
  weight = 40