# config/_default/params.toml

colorScheme = "blowfish"
defaultBackgroundImage = "bg3.jpg" # 全局背景(兜底用)，确保这张图在 static 里

[homepage]
  layout = "background"
  image = "hero.png"  <-- 必须改成和上面一样的新名字
  showRecent = true
  showRecentItems = 5
  showMore = true
  cardView = true

[article]
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = true
  showTaxonomies = false # 你之前要求的，不显示标签

[list]
  showHero = true
  heroStyle = "background"
  showSummary = true
  cardView = true  # <--- 这个开启后，那个丑陋的列表就会变成卡片
  
[footer]
  showCopyright = true